repo: https://github.com/CC-Digital-Innovation/Almanac.git
ssh_url: git@github.com:CC-Digital-Innovation/Almanac.git
branch: dev
project_root: src
image: almanac-dev
manifest_path: infra/cd/dev/deployment_dev.yml
pipeline: almanac-dev